version: '3'
services:
  mysql:
    image: 'mysql:5.6'
    restart: always
    environment:
      MYSQL_DATABASE: 'user'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
  springboot-app:
    build: .
    ports:
      - "8080:8080"
